language: ruby

sudo: required

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libvirt-dev
 - gem update bundler

script: bundle exec rake

matrix:
  fast_finish: true
  include:
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.0
      gemfile: Gemfile
    - rvm: 2.1.1
      gemfile: Gemfile
    - rvm: 2.2.0
      gemfile: Gemfile
    - rvm: 2.3.1
      gemfile: Gemfile
    - rvm: 2.4.5
      gemfile: Gemfile
    - rvm: 2.5.3
      gemfile: Gemfile
    - rvm: 2.6.0
      gemfile: Gemfile

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#ruby-fog"
    template:
      - "[#%{build_number}] %{message} %{build_url}"
      - "[#%{build_number}] %{commit} on %{branch} by %{author}"
      - "[#%{build_number}] %{compare_url}"
    on_success: always
    on_failure: always
    use_notice: false
